// Generated by scripts/refresh-data.py from pinned official sources.
export const DATA_RELEASE = {
  "checked": "2026-09-07",
  "wageRelease": "2025-11-19",
  "wageReference": "2023 to 2024 for most occupations; some 2024 or 2021",
  "employmentReference": "2023",
  "outlookHorizon": "2024 to 2033",
  "classification": "NOC 2021 v1.0",
  "activitySource": "OaSIS 2025 v1.0 (activity file v1.1)",
  "annualization": "Hourly medians × 40 hours/week × 52 weeks = 2,080 hours. Published annual figures are not multiplied.",
  "national": {
    "reference": "2026-08",
    "jobs": 21173100,
    "unit": "people",
    "adjustment": "Seasonally adjusted",
    "source": "Statistics Canada, Table 14-10-0310-01",
    "url": "https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410031001",
    "status": ""
  },
  "occupations": 516,
  "employmentCoverage": 485,
  "wageCoverage": 515,
  "exposureCoverage": 516
} as const
